### ISSUE TITLE
Browser Websockets example

### ISSUE THREAD

**Issue by aberba** [kiridaruma/kisaragi#1]
Does it support websockets like socket.io does? If yes, please show a demo.

**Comment by kiridaruma** [comment]
Kisaragi is not support socket.io because it uses unique protocol.
only Websocket support now.
but, if I receive many request, maybe I add socket.io support to Kisaragi.

if you have some request, please send issue or pull request.

I show websocket example on below.
**This is v0.2.0 (now current version), maybe it cannot use future version**
``` d
class TestCommand : Command{
    override @property string name(){ return "TestTestTest";}
    override void proc(Event eve){/* ... */}
}

void main(){
    auto kisaragi = new Kisaragi();
    kisaragi.addCommand(new TestCommand);
    kisaragi.setting = new Setting;
    kisaragi.run();
}
```

``` js
// you can set endpoint url at Setting.websocketEndpoint
let ws = new WebSocket("ws://example.com/ws"); 

// will excute TestCommand.proc
ws.send("{\"command\":"TestTestTest"}"); 
```
